[package]
name = "rust1brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
memchr = "2.7.2"


[profile.release-with-debug]
inherits = "release"
debug = true
